#!/usr/bin/env Rscript

# Designsystemet Component Generator
# ===================================
# This script generates R wrappers and JS bindings from:
# 1. The component-registry.yaml configuration
# 2. The custom-elements.json from @digdir/designsystemet-web
#
# Usage:
#   Rscript tools/generate.R [options]
#
# Options:
#   --help, -h           Show help
#   --summary            Print component summary
#   --dry-run            Preview without writing files
#   --component NAME     Generate only specified component
#   --clean              Remove generated files before generating
#
# NOTE: R generation is currently incomplete / not used in production.
#
# The hand-written R files group multiple components per file
# (e.g. ds-misc.R, ds-input.R, ds-typography.R, ds-details.R),
# whereas the generator assumes one file per component. Running R
# generation creates duplicate function definitions that break devtools::load_all().
#
# Until this is resolved, only JS generation (ds-bindings-generated.js) is
# useful. The generated JS is NOT loaded by ds_dependencies() yet — both files
# must be audited for selector/name conflicts before enabling.
#
# TODO: either
#   a) split hand-written files to one-per-component so generator output aligns, or
#   b) add a registry field (e.g. r_file: "ds-misc.R") so generator knows which
#      file owns each component and skips R output for existing files correctly.

library(yaml)
library(jsonlite)
library(whisker)

# Configuration
get_script_dir <- function() {

  args <- commandArgs(trailingOnly = FALSE)
 file_arg <- grep("--file=", args, value = TRUE)
  if (length(file_arg) > 0) {
    return(dirname(normalizePath(sub("--file=", "", file_arg))))
  }
  if (file.exists("tools/component-registry.yaml")) {
    return(normalizePath("tools"))
  }
  if (file.exists("component-registry.yaml")) {
    return(normalizePath("."))
  }
  stop("Cannot determine script directory. Run from package root or tools/ directory.")
}

TOOLS_DIR <- get_script_dir()
PACKAGE_ROOT <- dirname(TOOLS_DIR)
REGISTRY_PATH <- file.path(TOOLS_DIR, "component-registry.yaml")
TEMPLATES_DIR <- file.path(TOOLS_DIR, "templates")
R_OUTPUT_DIR <- file.path(PACKAGE_ROOT, "R")
JS_OUTPUT_DIR <- file.path(PACKAGE_ROOT, "inst", "www", "js")
GENERATED_DIR <- file.path(PACKAGE_ROOT, "R")

# Custom elements JSON path (from designsystemet build)
CUSTOM_ELEMENTS_PATH <- file.path(
  PACKAGE_ROOT, "..", "designsystemet", "packages", "web", "dist", "custom-elements.json"
)

# Null coalescing operator
`%||%` <- function(a, b) if (is.null(a)) b else a

# File header for generated R files
R_FILE_HEADER <- '# Generated by tools/generate.R - DO NOT EDIT BY HAND
# Edit tools/component-registry.yaml instead and re-run the generator.
# Generator version: 1.0.0
# Generated: %s

'

# File header for generated JS file
JS_FILE_HEADER <- '// Generated by tools/generate.R - DO NOT EDIT BY HAND
// Edit tools/component-registry.yaml instead and re-run the generator.
// Generator version: 1.0.0
// Generated: %s

// Designsystemet Shiny Input Bindings
// =====================================

'

# -----------------------------------------------------------------------------
# File Writing
# -----------------------------------------------------------------------------

write_file <- function(path, content, dry_run = FALSE) {
  is_hand_written <- file.exists(path) &&
    !grepl("Generated by tools/generate.R",
           readLines(path, n = 1, warn = FALSE))

  if (dry_run) {
    if (is_hand_written)
      message("  [DRY-RUN] Would SKIP (hand-written): ", path)
    else
      message("  [DRY-RUN] Would write: ", path)
    return(invisible(FALSE))
  }

  if (is_hand_written) {
    message("  Skipped (hand-written): ", path)
    return(invisible(FALSE))
  }

  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  writeLines(content, path)
  message("  Written: ", path)
  invisible(TRUE)
}

#' Generate file header with timestamp
make_r_header <- function() {
  sprintf(R_FILE_HEADER, format(Sys.time(), "%Y-%m-%d %H:%M:%S"))
}

make_js_header <- function() {
  sprintf(JS_FILE_HEADER, format(Sys.time(), "%Y-%m-%d %H:%M:%S"))
}

# -----------------------------------------------------------------------------
# Template Rendering
# -----------------------------------------------------------------------------

read_template <- function(name) {
  path <- file.path(TEMPLATES_DIR, paste0(name, ".tmpl"))
  if (!file.exists(path)) {
    stop("Template not found: ", path)
  }
  paste(readLines(path, warn = FALSE), collapse = "\n")
}

render_template <- function(template, data) {
  whisker::whisker.render(template, data)
}

# -----------------------------------------------------------------------------
# Registry Parsing
# -----------------------------------------------------------------------------

load_registry <- function() {
  if (!file.exists(REGISTRY_PATH)) {
    stop("Registry not found: ", REGISTRY_PATH)
  }
  yaml::read_yaml(REGISTRY_PATH)
}

load_custom_elements <- function() {
  if (!file.exists(CUSTOM_ELEMENTS_PATH)) {
    message("Note: custom-elements.json not found at ", CUSTOM_ELEMENTS_PATH)
    return(NULL)
  }
  jsonlite::fromJSON(CUSTOM_ELEMENTS_PATH, simplifyVector = FALSE)
}

# -----------------------------------------------------------------------------
# Code Generation Helpers
# -----------------------------------------------------------------------------

snake_to_camel <- function(x) {
  gsub("_(\\w)", "\\U\\1", x, perl = TRUE)
}

snake_to_title <- function(x) {
  words <- strsplit(x, "_")[[1]]
  paste(sapply(words, function(w) {
    paste0(toupper(substr(w, 1, 1)), substr(w, 2, nchar(w)))
  }), collapse = " ")
}

generate_signature <- function(params, has_input_id = FALSE, has_children = TRUE) {
  sig_parts <- character()

  if (has_input_id) {
    sig_parts <- c(sig_parts, "inputId")
  }

  # Add ... first if component has children
  if (has_children) {
    sig_parts <- c(sig_parts, "...")
  }

  for (p in params) {
    if (isTRUE(p$required)) {
      sig_parts <- c(sig_parts, p$name)
    } else {
      default <- if (is.null(p$default)) "NULL" else {
        if (is.character(p$default)) paste0('"', p$default, '"')
        else if (is.logical(p$default)) toupper(as.character(p$default))
        else as.character(p$default)
      }
      sig_parts <- c(sig_parts, paste0(p$name, " = ", default))
    }
  }

  # Add ... at end if no children
  if (!has_children) {
    sig_parts <- c(sig_parts, "...")
  }

  paste(sig_parts, collapse = ", ")
}

generate_attrib_mappings <- function(attrs, component) {
  mappings <- list()
  css_class <- component$css_class %||% ""

  mappings[[length(mappings) + 1]] <- list(
    HTML_ATTR = "class",
    R_VALUE = if (nchar(css_class) > 0) {
      sprintf('.ds_classes("%s", class)', css_class)
    } else {
      "class"
    },
    LAST = FALSE
  )

  for (attr in attrs) {
    r_value <- switch(
      attr$type %||% "string",
      "boolean" = sprintf('if (%s) "true" else NULL', attr$r_param),
      "boolean_attr" = sprintf("if (%s) NA else NULL", attr$r_param),
      "integer" = attr$r_param,
      "enum" = attr$r_param,
      attr$r_param
    )

    mappings[[length(mappings) + 1]] <- list(
      HTML_ATTR = sprintf("`%s`", attr$name),
      R_VALUE = r_value,
      LAST = FALSE
    )
  }

  if (length(mappings) > 0) {
    mappings[[length(mappings)]]$LAST <- TRUE
  }

  mappings
}

generate_validations <- function(attrs) {
  validations <- character()

  for (attr in attrs) {
    if (identical(attr$type, "enum") && !is.null(attr$values)) {
      values_str <- paste0('c("', paste(attr$values, collapse = '", "'), '")')
      validations <- c(validations, sprintf(
        '  %s <- match.arg(%s, %s)',
        attr$r_param, attr$r_param, values_str
      ))
    }
  }

  validations
}

# -----------------------------------------------------------------------------
# Update Function Generation
# -----------------------------------------------------------------------------

generate_update_function <- function(name, config) {
  r_function <- config$r_function %||% paste0("ds_", name)
  update_func <- paste0("update_", r_function)

  binding <- config$binding %||% "none"
  if (binding == "none") return(NULL)

  update_params <- list()
  if (binding %in% c("text", "checkbox", "select", "suggestion"))
    update_params <- c(update_params, list(list(NAME = "value", DESCRIPTION = "The new value.", LAST = FALSE)))
  if (binding == "select")
    update_params <- c(update_params, list(list(NAME = "choices", DESCRIPTION = "New choices vector.", LAST = FALSE)))
  if (binding == "tabs")
    update_params <- c(update_params, list(list(NAME = "selected", DESCRIPTION = "The tab value to select.", LAST = FALSE)))
  if (binding == "pagination") {
    update_params <- c(update_params, list(list(NAME = "current", DESCRIPTION = "The new current page.", LAST = FALSE)))
    update_params <- c(update_params, list(list(NAME = "total",   DESCRIPTION = "The new total pages.",   LAST = FALSE)))
  }

  if (length(update_params) == 0) return(NULL)
  update_params[[length(update_params)]]$LAST <- TRUE

  data <- list(
    TITLE         = snake_to_title(name),
    COMPONENT_NAME = name,
    FUNCTION_NAME = update_func,
    UPDATE_PARAMS = update_params
  )

  render_template(read_template("update.R"), data)
}

# -----------------------------------------------------------------------------
# CSS Component Generation
# -----------------------------------------------------------------------------

generate_css_component <- function(name, config, registry) {
  r_function  <- config$r_function %||% paste0("ds_", name)
  html_tag    <- config$html_tag
  css_class   <- config$css_class %||% ""
  attrs       <- config$attributes %||% list()
  binding     <- config$binding %||% "none"
  has_binding <- binding != "none"
  has_children <- !isTRUE(config$no_children)

  params <- lapply(attrs, function(a) {
    list(
      name        = a$r_param,
      description = a$description %||% sprintf("%s attribute", a$name),
      default     = a$default,
      required    = isTRUE(a$required)
    )
  })
  params <- c(params, list(list(name = "class", description = "Additional CSS classes",
                                default = NULL, required = FALSE)))

  validations      <- generate_validations(attrs)
  attrib_mappings  <- generate_attrib_mappings(attrs, config)
  sig              <- generate_signature(params, has_input_id = has_binding,
                                         has_children = has_children)

  # whisker PARAMS list
  tmpl_params <- lapply(params, function(p) {
    list(NAME        = p$name,
         DESCRIPTION = p$description,
         DEFAULT     = if (!is.null(p$default)) as.character(p$default) else FALSE)
  })

  data <- list(
    TITLE         = paste(snake_to_title(name), "Component"),
    DESCRIPTION   = sprintf("Create a %s using Designsystemet styles.", name),
    PARAMS        = tmpl_params,
    HAS_INPUT_ID  = has_binding,
    EXAMPLE       = sprintf('%s("Example")', r_function),
    FUNCTION_NAME = r_function,
    SIGNATURE     = sig,
    VALIDATIONS   = validations,
    ATTRIB_MAPPINGS = attrib_mappings,
    HAS_BINDING   = has_binding,
    HTML_TAG      = html_tag,
    HAS_CHILDREN  = FALSE,
    CHILDREN      = ""
  )

  render_template(read_template("wrapper.R"), data)
}

# -----------------------------------------------------------------------------
# Web Component Generation
# -----------------------------------------------------------------------------

generate_web_component <- function(name, config, registry, custom_elements) {
  r_function  <- config$r_function %||% paste0("ds_", name)
  tag         <- config$tag
  attrs       <- config$attributes %||% list()
  binding     <- config$binding %||% "none"
  has_binding <- binding != "none"

  # Merge attributes from custom-elements.json
  if (!is.null(custom_elements)) {
    for (module in custom_elements$modules %||% list()) {
      for (decl in module$declarations %||% list()) {
        if (identical(decl$tagName, tag)) {
          for (ce_attr in decl$attributes %||% list()) {
            exists <- any(sapply(attrs, function(a) a$name == ce_attr$name))
            if (!exists) {
              attrs <- c(attrs, list(list(
                name        = ce_attr$name,
                r_param     = gsub("-", "_", ce_attr$name),
                type        = ce_attr$type$text %||% "string",
                description = ce_attr$description %||% ""
              )))
            }
          }
          break
        }
      }
    }
  }

  params <- lapply(attrs, function(a) {
    list(name = a$r_param,
         description = a$description %||% sprintf("%s attribute", a$name),
         default = a$default, required = isTRUE(a$required))
  })
  params <- c(params, list(list(name = "class", description = "Additional CSS classes",
                                default = NULL, required = FALSE)))

  validations     <- generate_validations(attrs)
  css_class       <- config$css_class %||% tag
  attrib_mappings <- generate_attrib_mappings(attrs, list(css_class = css_class))
  sig             <- generate_signature(params, has_input_id = has_binding, has_children = TRUE)

  tmpl_params <- lapply(params, function(p) {
    list(NAME        = p$name,
         DESCRIPTION = p$description,
         DEFAULT     = if (!is.null(p$default)) as.character(p$default) else FALSE)
  })

  data <- list(
    TITLE           = paste(snake_to_title(name), "Web Component"),
    DESCRIPTION     = sprintf("Create a %s web component.", name),
    PARAMS          = tmpl_params,
    HAS_INPUT_ID    = has_binding,
    EXAMPLE         = sprintf('%s("content")', r_function),
    FUNCTION_NAME   = r_function,
    SIGNATURE       = sig,
    VALIDATIONS     = validations,
    ATTRIB_MAPPINGS = attrib_mappings,
    HAS_BINDING     = has_binding,
    HTML_TAG        = tag,
    HAS_CHILDREN    = FALSE,
    CHILDREN        = ""
  )

  render_template(read_template("wrapper.R"), data)
}

# -----------------------------------------------------------------------------
# JS Binding Generation
# -----------------------------------------------------------------------------

generate_js_binding <- function(name, config, binding_config) {
  binding_type <- config$binding
  if (is.null(binding_type) || binding_type == "none") return(NULL)

  bt <- binding_config[[binding_type]]
  if (is.null(bt)) {
    warning("Unknown binding type: ", binding_type, " for component: ", name)
    return(NULL)
  }

  selector <- if (!is.null(config$css_class)) {
    sprintf(".%s.ds-shiny-input", config$css_class)
  } else if (!is.null(config$tag)) {
    sprintf("%s.ds-shiny-input", config$tag)
  } else {
    warning("Cannot determine selector for: ", name)
    return(NULL)
  }

  binding_var   <- paste0("ds", tools::toTitleCase(snake_to_camel(name)))
  value_getter  <- config$value_getter %||% bt$value_getter %||% "    return el.value;"
  value_setter  <- config$value_setter %||% "    el.value = value;"
  event         <- config$binding_event %||% bt$event %||% "change"
  delegate      <- bt$delegate
  increment     <- isTRUE(bt$increment)

  receive_msg <- if (increment) {
    "    // action button: value managed client-side"
  } else {
    "    if (data.value !== undefined) this.setValue(el, data.value);\n    $(el).trigger('change');"
  }

  data <- list(
    COMPONENT_NAME  = name,
    BINDING_VAR     = binding_var,
    SELECTOR        = selector,
    VALUE_GETTER    = value_getter,
    VALUE_SETTER    = value_setter,
    DELEGATE        = if (!is.null(delegate)) delegate else FALSE,
    EVENT           = event,
    INCREMENT       = increment,
    RECEIVE_MESSAGE = receive_msg
  )

  render_template(read_template("binding.js"), data)
}

# -----------------------------------------------------------------------------
# Main Generation Functions
# -----------------------------------------------------------------------------

generate_all <- function(dry_run = FALSE, component_filter = NULL, clean = FALSE) {

  message("=== Designsystemet Component Generator ===\n")

  if (dry_run) {
    message("Running in DRY-RUN mode - no files will be written\n")
  }

  # Clean previously generated files if requested
  if (clean && !dry_run) {
    generated_files <- list.files(GENERATED_DIR, pattern = "\\.R$", full.names = TRUE)
    to_remove <- Filter(function(f) {
      first_line <- readLines(f, n = 1, warn = FALSE)
      grepl("Generated by tools/generate.R", first_line)
    }, generated_files)
    if (length(to_remove) > 0) {
      message("Cleaning ", length(to_remove), " previously generated R files...")
      file.remove(to_remove)
    }
  }

  message("Loading registry...")
  registry <- load_registry()

  message("Loading custom-elements.json...")
  custom_elements <- load_custom_elements()

  # Track what we generate
  r_files_written <- 0
  js_bindings <- character()
  update_functions <- character()

  # R/ always exists; no need to create it

  # Process CSS components
  message("\nGenerating CSS components...")
  for (name in names(registry$css_components)) {
    if (!is.null(component_filter) && name != component_filter) next

    config <- registry$css_components[[name]]
    r_function <- config$r_function %||% paste0("ds_", name)

    message("  - ", name, " -> ", r_function, "()")

    # Generate R wrapper
    r_code <- generate_css_component(name, config, registry)
    r_file <- file.path(GENERATED_DIR, paste0(gsub("_", "-", r_function), ".R"))

    # Generate update function if needed
    update_code <- generate_update_function(name, config)
    if (!is.null(update_code)) {
      r_code <- paste0(r_code, "\n", update_code)
      update_functions <- c(update_functions, name)
    }

    # Write R file
    content <- paste0(make_r_header(), r_code)
    if (write_file(r_file, content, dry_run)) {
      r_files_written <- r_files_written + 1
    }

    # Generate JS binding if needed
    if (!is.null(config$binding) && config$binding != "none") {
      binding_code <- generate_js_binding(name, config, registry$binding_types)
      if (!is.null(binding_code)) {
        js_bindings <- c(js_bindings, binding_code)
      }
    }
  }

  # Process web components
  message("\nGenerating web components...")
  for (name in names(registry$web_components)) {
    if (!is.null(component_filter) && name != component_filter) next

    config <- registry$web_components[[name]]
    r_function <- config$r_function %||% paste0("ds_", name)

    message("  - ", name, " -> ", r_function, "()")

    # Generate R wrapper
    r_code <- generate_web_component(name, config, registry, custom_elements)
    r_file <- file.path(GENERATED_DIR, paste0(gsub("_", "-", r_function), ".R"))

    # Generate update function if needed
    update_code <- generate_update_function(name, config)
    if (!is.null(update_code)) {
      r_code <- paste0(r_code, "\n", update_code)
      update_functions <- c(update_functions, name)
    }

    # Write R file
    content <- paste0(make_r_header(), r_code)
    if (write_file(r_file, content, dry_run)) {
      r_files_written <- r_files_written + 1
    }

    # Generate JS binding if needed
    if (!is.null(config$binding) && config$binding != "none") {
      binding_code <- generate_js_binding(name, config, registry$binding_types)
      if (!is.null(binding_code)) {
        js_bindings <- c(js_bindings, binding_code)
      }
    }
  }

  # Write combined JS bindings file
  if (length(js_bindings) > 0) {
    message("\nGenerating JS bindings file...")
    js_content <- paste0(
      make_js_header(),
      paste(js_bindings, collapse = "\n\n")
    )
    js_file <- file.path(JS_OUTPUT_DIR, "ds-bindings-generated.js")
    write_file(js_file, js_content, dry_run)
  }

  # Summary
  message("\n=== Generation Complete ===")
  message("  R files: ", r_files_written, " (in R/)")
  message("  JS bindings: ", length(js_bindings))
  message("  Update functions: ", length(update_functions))

  if (!dry_run) {
    message("\nGenerated files are in:")
    message("  R wrappers: ", GENERATED_DIR)
    message("  JS bindings: ", file.path(JS_OUTPUT_DIR, "ds-bindings.js"))
    message("\nNote: Hand-written R files (no '# Generated' header) are never overwritten.")
    message("Note: ds-bindings.js is fully regenerated each run.")
  }

  invisible(list(
    r_files = r_files_written,
    js_bindings = length(js_bindings),
    update_functions = update_functions
  ))
}

print_summary <- function() {
  registry <- load_registry()

  cat("\n=== Designsystemet Component Summary ===\n\n")

  cat("CSS Components (", length(registry$css_components), "):\n", sep = "")
  for (name in sort(names(registry$css_components))) {
    config <- registry$css_components[[name]]
    r_func <- config$r_function %||% paste0("ds_", name)
    binding <- config$binding %||% "none"
    cat(sprintf("  %-25s -> %-25s [%s]\n", name, r_func, binding))
  }

  cat("\nWeb Components (", length(registry$web_components), "):\n", sep = "")
  for (name in sort(names(registry$web_components))) {
    config <- registry$web_components[[name]]
    r_func <- config$r_function %||% paste0("ds_", name)
    tag <- config$tag
    binding <- config$binding %||% "none"
    cat(sprintf("  %-25s -> %-25s <%s> [%s]\n", name, r_func, tag, binding))
  }

  cat("\n")
}

# -----------------------------------------------------------------------------
# CLI Entry Point
# -----------------------------------------------------------------------------

if (!interactive()) {
  args <- commandArgs(trailingOnly = TRUE)

  if ("--help" %in% args || "-h" %in% args) {
    cat("
Designsystemet Component Generator

Usage:
  Rscript tools/generate.R [options]

Options:
  --help, -h           Show this help message
  --summary            Print component summary from registry
  --dry-run            Preview generation without writing files
  --clean              Remove previously generated R files before regenerating
  --component NAME     Generate only the specified component

Output:
  R wrappers are written to: R/
  JS bindings are written to: inst/www/js/ds-bindings.js

Examples:
  Rscript tools/generate.R --summary
  Rscript tools/generate.R --dry-run
  Rscript tools/generate.R --clean
  Rscript tools/generate.R --component button

")
    quit(status = 0)
  }

  if ("--summary" %in% args) {
    print_summary()
    quit(status = 0)
  }

  # Parse options
  dry_run <- "--dry-run" %in% args
  clean <- "--clean" %in% args

  component_filter <- NULL
  comp_idx <- which(args == "--component")
  if (length(comp_idx) > 0 && comp_idx < length(args)) {
    component_filter <- args[comp_idx + 1]
  }

  # Run generation
  result <- generate_all(
    dry_run = dry_run,
    component_filter = component_filter,
    clean = clean
  )

  quit(status = 0)
}
